
token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJHcmVlbiIsImF1dGgiOiIiLCJleHAiOjE1NjY1MzIyMDgsImlhdCI6MTU2Mzk0MDE0OCwiaXNzIjoiR3JlZW4iLCJzdWIiOjEwMDAwMTcwMH0.z_V0F5KIJ3xeVe9S2SVsoWA-AB1g795VCzR-dAut2dM"

username: "13100010001"
password: "zxc123.."

user_id: '100001700'


